apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cicd-pipeline2
  annotations:
    scenarios.ai.sap.com/description: "CI-CD Pipelines for Pipeline Corrosion Analytics"
    scenarios.ai.sap.com/name: "cicd-pipeline-corrosion-analytics"
    executables.ai.sap.com/description: "Continuous integration and delivery pipeline"
    executables.ai.sap.com/name: "cicd-serve-exec"
  labels:
    scenarios.ai.sap.com/id: "cicd-pipeline-corrosion-analytics"
    executables.ai.sap.com/id: "cicd-serve-exec"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts:
      - name: pipelinecorrdata
      - name: pipelinecorrcred
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: "docker.io/yoshidj/pipeline-corr-cicd:serve"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.pipelinecorrcred}}"